### ISSUE TITLE
build not working

### ISSUE THREAD

**Issue by debianmaster** [rancher/rio#237]
```sh
cjonagam$ rio ps
NAME                         CREATED         ENDPOINT                                                                                REVISIONS   SCALE     WEIGHT    DETAIL
default/distracted-jepsen8   2 hours ago                                                                                             v0          0/1       100%      v0 NotReady; v0 waiting on build
```

```
chakwifi:manage.example.io cjonagam$ rio ps
NAME                         CREATED              ENDPOINT                                                                                REVISIONS   SCALE     WEIGHT    DETAIL
default/distracted-jepsen8   2 hours ago                                                                                                  v0          0/1       100%      v0 NotReady; v0 waiting on build
default/svc                  2 hours ago          http://test.example.io:9080, http://test.bgk.example.io:9080, http://test1.bgk.example.io:9080   v0          3         100%
default/wizardly-wright5     About a minute ago                                                                                           v0          0/1       100%      v0 NotReady; v0 waiting on build
$ rio build logs default/distracted-jepsen8
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/rancher/rio/cli/cmd/builds.(*Logs).Run(0x31f6d90, 0xc0004c7800, 0x0, 0x0)
	/go/src/github.com/rancher/rio/cli/cmd/builds/logs.go:34 +0xb2d
github.com/rancher/rio/cli/pkg/builder.Command.func1(0xc0004c7800, 0xc00014e420, 0x223fa38)
	/go/src/github.com/rancher/rio/cli/pkg/builder/builder.go:137 +0x91
github.com/rancher/rio/cli/pkg/clicontext.Wrap.func1(0xc0002d26e0, 0xc000085a00, 0xc0002d26e0)
	/go/src/github.com/rancher/rio/cli/pkg/clicontext/clicontext.go:29 +0x9e
github.com/rancher/rio/vendor/github.com/urfave/cli.HandleAction(0x2018920, 0xc0000be420, 0xc0002d26e0, 0x0, 0xc000085a40)
	/go/src/github.com/rancher/rio/vendor/github.com/urfave/cli/app.go:501 +0xc8
github.com/rancher/rio/vendor/github.com/urfave/cli.Command.Run(0xc0000c0384, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x22439ee, 0xb, 0xc0004a8150, ...)
	/go/src/github.com/rancher/rio/vendor/github.com/urfave/cli/command.go:165 +0x487
github.com/rancher/rio/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc000226e00, 0xc0000ccf20, 0x0, 0x0)
	/go/src/github.com/rancher/rio/vendor/github.com/urfave/cli/app.go:383 +0x850
github.com/rancher/rio/vendor/github.com/urfave/cli.Command.startApp(0x223fa08, 0x6, 0x223eb8b, 0x5, 0x0, 0x0, 0x0, 0x224bb20, 0x14, 0x0, ...)
	/go/src/github.com/rancher/rio/vendor/github.com/urfave/cli/command.go:330 +0x821
github.com/rancher/rio/vendor/github.com/urfave/cli.Command.Run(0x223fa08, 0x6, 0x223eb8b, 0x5, 0x0, 0x0, 0x0, 0x224bb20, 0x14, 0x0, ...)
	/go/src/github.com/rancher/rio/vendor/github.com/urfave/cli/command.go:103 +0x809
github.com/rancher/rio/vendor/github.com/urfave/cli.(*App).Run(0xc000446000, 0xc0000bc000, 0x4, 0x4, 0x0, 0x0)
	/go/src/github.com/rancher/rio/vendor/github.com/urfave/cli/app.go:259 +0x6e3
main.main()
	/go/src/github.com/rancher/rio/cli/main.go:241 +0x20e7
```

**Comment by debianmaster** [comment]
```
$ rio --version
rio version v0.1.1-rc1 (cdb75cf1)
```

**Comment by StrongMonkey** [comment]
This should be fixed in the latest release. Any chance you are still have the issue? @debianmaster

**Comment by debianmaster** [comment]
@StrongMonkey   i'll try nd let you know
