### ISSUE TITLE
`rio route` and `rio services` doesn't support timeout 

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rio#684]
Right now there is no way to configure timeout setting to gloo gateway for routes and services.

**Comment by StrongMonkey** [comment]
This is not urgent to test for v0.6.0. We basically added parameter for router and services you can configure timeout for each rule.

**Comment by rancher-max** [comment]
`rio run --request-timeout-seconds 1 -n ghout -p 8080 https://github.com/rancher-max/rio-demo' causes a panic in the rio-controller and it becomes broken. Had to uninstall rio and reinstall to get it working again.

```
rio-controller | E1107 18:45:33.311015       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
rio-controller | goroutine 873 [running]:
rio-controller | github.com/rancher/rio/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1c13a80, 0x3433e10)
rio-controller | 	/go/src/github.com/rancher/rio/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
rio-controller | github.com/rancher/rio/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
rio-controller | 	/go/src/github.com/rancher/rio/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
rio-controller | panic(0x1c13a80, 0x3433e10)
rio-controller | 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
rio-controller | github.com/rancher/rio/modules/gloo/pkg/vsfactory.(*VirtualServiceFactory).ForRevision(0xc000ebcc00, 0xc0005ac000, 0xc000c9e180, 0x1fd7c90, 0xc00224ab98, 0xc00224aad0, 0xc00224ac78)
rio-controller | 	/go/src/github.com/rancher/rio/modules/gloo/pkg/vsfactory/revision.go:23 +0x5c1
rio-controller | github.com/rancher/rio/modules/gloo/controller/service.(*handler).generate(0xc0006302a0, 0xc0005ac000, 0x0, 0x0, 0xc0008f648b, 0x5, 0xc0008f6590, 0x2, 0x0, 0xc001773250, ...)
rio-controller | 	/go/src/github.com/rancher/rio/modules/gloo/controller/service/handler.go:45 +0x6f
rio-controller | github.com/rancher/rio/pkg/generated/controllers/rio.cattle.io/v1.(*serviceGeneratingHandler).Handle(0xc000b59f20, 0xc0005ac000, 0x0, 0x0, 0xc0008f648b, 0x5, 0xc0008f6590, 0x2, 0x0, 0xc001773250, ...)
rio-controller | 	/go/src/github.com/rancher/rio/pkg/generated/controllers/rio.cattle.io/v1/service.go:315 +0x90
rio-controller | github.com/rancher/rio/pkg/generated/controllers/rio.cattle.io/v1.(*serviceStatusHandler).sync(0xc000630570, 0xc0005cca60, 0x13, 0xc0000f1b00, 0xc0003e5f70, 0x0, 0x0)
rio-controller | 	/go/src/github.com/rancher/rio/pkg/generated/controllers/rio.cattle.io/v1/service.go:282 +0x11f
rio-controller | github.com/rancher/rio/pkg/generated/controllers/rio.cattle.io/v1.FromServiceHandlerToHandler.func1(0xc0005cca60, 0x13, 0x21ffee0, 0xc0000f1b00, 0x1, 0xc0003e5f70, 0x0, 0x1)
rio-controller | 	/go/src/github.com/rancher/rio/pkg/generated/controllers/rio.cattle.io/v1/service.go:101 +0x65
rio-controller | github.com/rancher/rio/vendor/github.com/rancher/wrangler/pkg/generic.(*Handlers).Handle(0xc000493560, 0xc0005cca60, 0x13, 0x21ffee0, 0xc0000f1b00, 0x1c5dbe0, 0x1ed0ba0, 0xc000228100, 0x21ffee0)
rio-controller | 	/go/src/github.com/rancher/rio/vendor/github.com/rancher/wrangler/pkg/generic/handlers.go:27 +0x100
rio-controller | github.com/rancher/rio/vendor/github.com/rancher/wrangler/pkg/generic.(*Controller).syncHandler(0xc0002c51f0, 0xc0005cca60, 0x13, 0x138abf1, 0xc0008f77e0)
rio-controller | 	/go/src/github.com/rancher/rio/vendor/github.com/rancher/wrangler/pkg/generic/controller.go:175 +0xdb
rio-controller | github.com/rancher/rio/vendor/github.com/rancher/wrangler/pkg/generic.(*Controller).processSingleItem(0xc0002c51f0, 0x1b65460, 0xc000128e50, 0x0, 0x0)
rio-controller | 	/go/src/github.com/rancher/rio/vendor/github.com/rancher/wrangler/pkg/generic/controller.go:156 +0xf0
rio-controller | github.com/rancher/rio/vendor/github.com/rancher/wrangler/pkg/generic.(*Controller).processNextWorkItem(0xc0002c51f0, 0xb)
rio-controller | 	/go/src/github.com/rancher/rio/vendor/github.com/rancher/wrangler/pkg/generic/controller.go:133 +0x51
rio-controller | github.com/rancher/rio/vendor/github.com/rancher/wrangler/pkg/generic.(*Controller).runWorker(0xc0002c51f0)
rio-controller | 	/go/src/github.com/rancher/rio/vendor/github.com/rancher/wrangler/pkg/generic/controller.go:122 +0x2b
rio-controller | github.com/rancher/rio/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00081ace0)
rio-controller | 	/go/src/github.com/rancher/rio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
rio-controller | github.com/rancher/rio/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00081ace0, 0x3b9aca00, 0x0, 0x1a8e501, 0xc000039980)
rio-controller | 	/go/src/github.com/rancher/rio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
rio-controller | github.com/rancher/rio/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00081ace0, 0x3b9aca00, 0xc000039980)
rio-controller | 	/go/src/github.com/rancher/rio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
rio-controller | created by github.com/rancher/rio/vendor/github.com/rancher/wrangler/pkg/generic.(*Controller).run
rio-controller | 	/go/src/github.com/rancher/rio/vendor/github.com/rancher/wrangler/pkg/generic/controller.go:104 +0x178
rio-controller | panic: runtime error: invalid memory address or nil pointer dereference [recovered]
rio-controller | 	panic: runtime error: invalid memory address or nil pointer dereference
rio-controller | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18c6ea1]
rio-controller | 
rio-controller | goroutine 873 [running]:
rio-controller | github.com/rancher/rio/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
rio-controller | 	/go/src/github.com/rancher/rio/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
rio-controller | panic(0x1c13a80, 0x3433e10)
rio-controller | 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
rio-controller | github.com/rancher/rio/modules/gloo/pkg/vsfactory.(*VirtualServiceFactory).ForRevision(0xc000ebcc00, 0xc0005ac000, 0xc000c9e180, 0x1fd7c90, 0xc00224ab98, 0xc00224aad0, 0xc00224ac78)
rio-controller | 	/go/src/github.com/rancher/rio/modules/gloo/pkg/vsfactory/revision.go:23 +0x5c1
rio-controller | github.com/rancher/rio/modules/gloo/controller/service.(*handler).generate(0xc0006302a0, 0xc0005ac000, 0x0, 0x0, 0xc0008f648b, 0x5, 0xc0008f6590, 0x2, 0x0, 0xc001773250, ...)
rio-controller | 	/go/src/github.com/rancher/rio/modules/gloo/controller/service/handler.go:45 +0x6f
rio-controller | github.com/rancher/rio/pkg/generated/controllers/rio.cattle.io/v1.(*serviceGeneratingHandler).Handle(0xc000b59f20, 0xc0005ac000, 0x0, 0x0, 0xc0008f648b, 0x5, 0xc0008f6590, 0x2, 0x0, 0xc001773250, ...)
rio-controller | 	/go/src/github.com/rancher/rio/pkg/generated/controllers/rio.cattle.io/v1/service.go:315 +0x90
rio-controller | github.com/rancher/rio/pkg/generated/controllers/rio.cattle.io/v1.(*serviceStatusHandler).sync(0xc000630570, 0xc0005cca60, 0x13, 0xc0000f1b00, 0xc0003e5f70, 0x0, 0x0)
rio-controller | 	/go/src/github.com/rancher/rio/pkg/generated/controllers/rio.cattle.io/v1/service.go:282 +0x11f
rio-controller | github.com/rancher/rio/pkg/generated/controllers/rio.cattle.io/v1.FromServiceHandlerToHandler.func1(0xc0005cca60, 0x13, 0x21ffee0, 0xc0000f1b00, 0x1, 0xc0003e5f70, 0x0, 0x1)
rio-controller | 	/go/src/github.com/rancher/rio/pkg/generated/controllers/rio.cattle.io/v1/service.go:101 +0x65
rio-controller | github.com/rancher/rio/vendor/github.com/rancher/wrangler/pkg/generic.(*Handlers).Handle(0xc000493560, 0xc0005cca60, 0x13, 0x21ffee0, 0xc0000f1b00, 0x1c5dbe0, 0x1ed0ba0, 0xc000228100, 0x21ffee0)
rio-controller | 	/go/src/github.com/rancher/rio/vendor/github.com/rancher/wrangler/pkg/generic/handlers.go:27 +0x100
rio-controller | github.com/rancher/rio/vendor/github.com/rancher/wrangler/pkg/generic.(*Controller).syncHandler(0xc0002c51f0, 0xc0005cca60, 0x13, 0x138abf1, 0xc0008f77e0)
rio-controller | 	/go/src/github.com/rancher/rio/vendor/github.com/rancher/wrangler/pkg/generic/controller.go:175 +0xdb
rio-controller | github.com/rancher/rio/vendor/github.com/rancher/wrangler/pkg/generic.(*Controller).processSingleItem(0xc0002c51f0, 0x1b65460, 0xc000128e50, 0x0, 0x0)
rio-controller | 	/go/src/github.com/rancher/rio/vendor/github.com/rancher/wrangler/pkg/generic/controller.go:156 +0xf0
rio-controller | github.com/rancher/rio/vendor/github.com/rancher/wrangler/pkg/generic.(*Controller).processNextWorkItem(0xc0002c51f0, 0xb)
rio-controller | 	/go/src/github.com/rancher/rio/vendor/github.com/rancher/wrangler/pkg/generic/controller.go:133 +0x51
rio-controller | github.com/rancher/rio/vendor/github.com/rancher/wrangler/pkg/generic.(*Controller).runWorker(0xc0002c51f0)
rio-controller | 	/go/src/github.com/rancher/rio/vendor/github.com/rancher/wrangler/pkg/generic/controller.go:122 +0x2b
rio-controller | github.com/rancher/rio/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00081ace0)
rio-controller | 	/go/src/github.com/rancher/rio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
rio-controller | github.com/rancher/rio/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00081ace0, 0x3b9aca00, 0x0, 0x1a8e501, 0xc000039980)
rio-controller | 	/go/src/github.com/rancher/rio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
rio-controller | github.com/rancher/rio/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00081ace0, 0x3b9aca00, 0xc000039980)
rio-controller | 	/go/src/github.com/rancher/rio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
rio-controller | created by github.com/rancher/rio/vendor/github.com/rancher/wrangler/pkg/generic.(*Controller).run
rio-controller | 	/go/src/github.com/rancher/rio/vendor/github.com/rancher/wrangler/pkg/generic/controller.go:104 +0x178
```

**Comment by davidnuzik** [comment]
@rancher-max try again in latest (master) and if still happens move back to Working

**Comment by rancher-max** [comment]
same behavior with latest master

**Comment by StrongMonkey** [comment]
@rancher-max available to test on master.

**Comment by rancher-max** [comment]
Working with latest master. Using the same above command, now it does not panic and times out (giving 504) when the request takes longer than the time specified.
